name: 🚀 Deploy to bikrihoy.com on push
on:
 push:
  branches: kids.bikrihoy.com

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.bikrihoy.com
        username: u498337615.kids
        password: ${{ secrets.KIDS_FTP_PASSWORD }}
